name: "Dummy Commit"
on:
  pull_request:
    branches:
      - 'main'
    

jobs:
  dummy-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: "Push the changes"
      run: |
        git commit --allow-empty -m "Trigger Preview"
        git push 
