name: "Dummy Commit"
on:
  pull_request:
    branches:
      - 'main'
    

jobs:
  dummy-commit:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'sudhanshu456' }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: "Configure git"
      run: |
        git config user.name 'Sudhanshu Prajapati'
        git config user.email 'spsupraj2d@gmail.com'
    - name: "Push the changes"
      run: |
          git commit --allow-empty -m "Trigger Preview"
          git push 
        